### ISSUE TITLE
Support modules with semver version

### ISSUE THREAD

**Issue by Sutharsan** [drupal-composer/drupal-l10n#13]
For example, when downloading the search404 module (2.0.0) drupal-l10n attempts to download the translation from `http://ftp.drupal.org/files/translations/8.x/search404/search404-8.x-2.0.nl.po`, while it should actually download this file: `search404-2.0.0.nl.po`

**Comment by FlorentTorregrosa** [comment]
Hello,

Thanks a lot for opening this issue.

I have manually reproduced the problem.

I will try to provide a failing automated test and a fix for that.

**Comment by FlorentTorregrosa** [comment]
I don't think there is the possibility to know if the module is using semantic versioning or not.

So, I will have to adapt:
* https://github.com/drupal-composer/drupal-l10n/blob/master/src/Handler.php#L320 (extractPackageVersion method) to prepare both semantic version and "classic Drupal" version
* adapt the code to pass the new variable/structure until reaching https://github.com/drupal-composer/drupal-l10n/blob/master/src/FileFetcher.php#L160 (getUrl method) and try both urls.

**Comment by FlorentTorregrosa** [comment]
PR #14 opened

**Comment by FlorentTorregrosa** [comment]
I have made the modification and tests are passing locally. But I saw with the PR that Travis integration is broken. It is triggered but Travis result is not sent back to Github.

**Comment by FlorentTorregrosa** [comment]
I pushed the fix on the PR too, and pinged @webflo on Slack for help with Travis integration.

**Comment by FlorentTorregrosa** [comment]
PR merged. And new release done.
