### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by mriffault** [drupal-composer/drupal-l10n#22]
I'm trying to use this plugin on a fresh new D9 project. It seems that the plugin rely on Core version to fetch for translations in the http://ftp.drupal.org/files/translations directory, so it's trying to get translation for 9.x and unfortunately this directory in the FTP do not provide a lot of contrib modules translations for the moment.

Should we fetch translations from 8.x for D9? Or maybe we could provide another option in the extra section to be able to override the Core version?

**Comment by mriffault** [comment]
Created the suggested change as a PR : #23

**Comment by FlorentTorregrosa** [comment]
Hello,

Thanks to have highlighted this problem.

Maybe instead to have to choose 8.x when on 9.x, if the file is not found on 9.x, try with 8.x. Is this approach ok?

But there will be the problem then on 10.x too I think. Maybe a recursive try from current core version 12.x for example to 8.x with 11.x, 10.x, 9.x can be made.

**Comment by FlorentTorregrosa** [comment]
I sent a message on Slack https://drupal.slack.com/archives/C51GNJG91/p1612089588041400 to ask if further evolution will occur.

From what I see, as semver branch translations and core D9 is in the 8.x, I will add a condition on the 8.x+ core version and that's it. No options needed.

**Comment by FlorentTorregrosa** [comment]
PR are merged and releases done for 1.0.x and 2.0.x.
