### ISSUE TITLE
Mismatch in download URL

### ISSUE THREAD

**Issue by petergerner** [drupal-composer/drupal-l10n#31]
When I download a translation file via `composer drupal:l10n`, it fails with

```
drupal-7.78.0.hu.po (https://ftp.drupal.org/files/translations/all/drupal/drupal-7.78.0.hu.po):
Could not download the file in any managed formats. This is certainly due to a non-existing translation file.
```

The correct download URL seems to be `https://ftp.drupal.org/files/translations/7.x/drupal/drupal-7.78.hu.po`, note the diiiference in URLs at: translations/**all**/drupal and translations/**7.x**/drupal

**Comment by FlorentTorregrosa** [comment]
Hello, Thanks for reporting this bug. It was introduced when doing D9 compatibility. I had been given the info that all translations are now in all, but it seems that it only applied starting from D8.

**Comment by FlorentTorregrosa** [comment]
Fixed in https://github.com/drupal-composer/drupal-l10n/pull/32 and https://github.com/drupal-composer/drupal-l10n/pull/33.

I will make new releases.
