### ISSUE TITLE
Prepare first version

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupal-composer/drupal-l10n#7]
TODO:
* Travis CI config review
* Github settings review
* Connection with Packagist.org.

**Comment by webflo** [comment]
Sure, see you later at the venue.

**Comment by FlorentTorregrosa** [comment]
Thanks @webflo!

**Comment by FlorentTorregrosa** [comment]
At least a first tag should be done... I forgot about that.

**Comment by FlorentTorregrosa** [comment]
Release done: https://github.com/drupal-composer/drupal-l10n/releases/tag/1.0.0
